server:
  port: 8086
spring:
  application:
    name: auto-javadocs
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html