server:
  port: 8087

spring:
  application:
    name: junit_generator

  ai:
    model:
      chat: ollama # enable ollama chat model
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs